### ISSUE TITLE
Adding a tag

### ISSUE THREAD

**Issue by Accio** [niaid/dsb#15]
Will you please add a tag/version so that conda users can build a skeleton? 

The idea is explained here: https://github.com/conda/conda/issues/6674

Thanks.

**Comment by MattPM** [comment]
Hi @Accio the package is currently submitted to CRAN and pending inspection, it will hopefully be hosted there within the next day or two. I was going to wait to tag a clean release until it is accepted and hosted on CRAN to add that to release notes and make sure the git repo and CRAN binaries are identical. (normalization code will be identical, just pending changes to formatting of Description file etc.) Similar idea discussed here: https://github.com/r-lib/devtools/issues/1198

However, I can tag a release now and update it if this is time sensitive. For the conda skeleton, do you know if the git repo has to have a version of the compiled binaries uploaded? [see section 7 here](https://docs.github.com/en/free-pro-team@latest/github/administering-a-repository/managing-releases-in-a-repository). 

-Matt

**Comment by MattPM** [comment]
@Accio dsb is now on CRAN as of this morning. I just added a release. Please let me know if this is sufficient to build a skeleton. Thanks.

**Comment by MattPM** [comment]
@Accio closing this–please reopen if further assistance or action required on my end. Thanks for your interest.

**Comment by Accio** [comment]
Perfect, thank you!

Von meinem iPad gesendet
