### ISSUE TITLE
DropletUtils::EmptyDrops?

### ISSUE THREAD

**Issue by bbimber** [niaid/dsb#17]
hello - 
i notice in your example you are setting somewhat manual filter thresholds on the ADT and GEX droplets. have you tried using other algorithms, like DropUtils::emptyDrops (https://rdrr.io/github/MarioniLab/DropletUtils/man/emptyDrops.html) to differentiate true cells from background?

**Comment by MattPM** [comment]
Overall with CITE-seq protein data it is easier to see the cells vs empty drops than if you have mRNA alone. With the method shown in the vignette using cutoffs based on surface  protein count library size then additional QC to make sure there are no contaminating droplets,  there is often more than an order of magnitude separation in the cells from the background. ADT library size in cells is pretty large and the protein counts themselves are not at all zero inflated the background is usually very clear. This is true in our hands with panels >80 proteins all the way down to some of the 10X datasets with just 14 proteins, but I could potentially see this being an issue if you only measured a a few proteins. I like the emptyDrops method it is cool, but based on your other post, you have multiplexing data. I am not certain if the distributional assumptions in emptyDrops work for data with many doublets and how that would impact how one would tune the parameters. 

We have also looked at protein and mRNA expression within the population we define as negative and even the droplets at the higher end of mRNA levels within these droplets had no clear cell populations and expression appeared to just be random noise, so at least in the data we have analyzed it did not seem like we were removing cells using these simple thresholds.

**Comment by bbimber** [comment]
@Matt-PM OK, thanks. We need to get further down the line exploring this in our hands. I'm just now getting to running this on a more realistic input. I ideally want to run this in a more automatic-headless way (we have a lot of data), so choosing those cutoffs in a more automatic manner would be preferable than inspecting a plot per sample. Maybe I'm missing something. I see your point about comparing with GEX data and we would definitely have that whitelist of passing GEX barcodes.

**Comment by MattPM** [comment]
Hi @bbimber yes, good idea and automatic background detection is something we considered but currently experiment designs are so unique (number of sample, antibodies, doublet percentage) that it is more flexible to just let the user define background with simple protein library size thresholds (+ RNA based QC on e.g. gene number / mRNA library size MT gene percentage etc, which has to be done for any experiment anyway). One thing to note--you definitely wouldn't want to inspect a plot per sample--it would be one plot per *entire experiment*. Usually with multiplexing, you are barcoding all the samples, pooling them together, staining with CITE-seq antibodies, then loading the pooled cells across multiple lanes of 10x. To demultiplex, you then combine all the data from multiple lanes into a single matrix for each assay (ADT, HTO, RNA). Then you would define the background and the cells from all that combined data as described in the vignette in the main section or the multiplexing section.

So for example, in [this paper](https://www.nature.com/articles/s41591-020-0769-8) we had 20 samples from 20 unique donors, after hashing the donors and pooling we split the pool across n=12 lanes of the 10x. We combined the data for each assay from each lane and defined singlets cells and background droplets using  *all* the droplets from the merged data across 12 lanes (see my reply to your other post for additional details) as described above and in the vignette--so I only made that plot and did QC on the droplets one time, not once for each sample. Let me know if that makes sense and happy to advise further.

**Comment by bbimber** [comment]
Thanks. I was using 'sample' a bit loosely. We are most interesting in pooling lanes/experiments. In our case each lane often does have multiple samples multplexed together, and i get your point about that being one staining instance. It's the cross-lane / cross-experiment sample normalization I was referring to.   

We're generating some data with empty drops on the ADTs to see how this looks (per 10x lane).
