### ISSUE TITLE
Filtering cells of multiplexed experiment stained with TotalSeq-A universal panel

### ISSUE THREAD

**Issue by MikhaelManurung** [niaid/dsb#21]
Dear author,

Thank you for writing the package.

I apologise in advance if my question is naive or has been asked by someone else. I am new to the field and I am paralysed by the many forking paths of analysis that we can do.

I have a multiplexed experiment stained with TotalSeq-A universal panel. Given this design, if I understand correctly, I should perform a very minimal filtering of the unfiltered cellranger matrix and then directly demultiplex instead of performing droplet filtering (eg. `EmptyDrops`). After selecting singlets and negative droplets, I can normalise my CITE-Seq data using `dsb` and then perform gene-based QC (% mito, etc.).

Is this correct?

Many thanks in advance.

**Comment by MattPM** [comment]
Hi @MikhaelManurung yes, what you outlined is exactly what I'd recommend. After demultiplexing, you should do some QC filtering of both the singlets *and* the negative droplets called by demultiplexing (i.e. for the negatives, removing outliers with a large mRNA library size and for the singlets, running normal quality control like you would for any scRNAseq experiment) prior to normalizing with dsb. That is the simplest method for multiplexing experiments and is what I'd recommend.  

FWIW, another method for extracting the negative drops is to just use a threshold. Often a large population of negative droplets (orders of magnitude more drops than the number of cells you loaded) are quite obvious based on the ADT library size distribution of the Cell Ranger raw output. One can make a cutoff for calling negative drops below some ADT library size threshold before demultiplexing, then after demultiplexing the cells, you can further filter that negative population to make sure you remove any barcodes that were classified as singlets for example. In our data, we tried that as well as just using the barcodes classified as "Negative" from demultiplexing and the results were essentially equivalent (See supplemental figures 1 and 9 in the updated preprint: https://www.biorxiv.org/content/10.1101/2020.02.24.963603v3.full.pdf).

**Comment by MikhaelManurung** [comment]
Alright, that makes a lot of sense. Thanks!
