### ISSUE TITLE
object 'count_prot' not found 

### ISSUE THREAD

**Issue by johaab** [niaid/dsb#25]
Hi! I was trying to run your vignette and the code fails at Step III (option b) because "count_prot" hasn't been defined anywhere. Could you please indicate what this variable corresponds to exactly and maybe update your vignette?

**Comment by MattPM** [comment]
Hi @johaab thanks for finding that, `count_prot` should be the raw protein counts x cells data which is `cells_mtx_rawprot` defined earlier in the vignette. That section is just making an object of the raw protein x cells data to define an `Altexp` object which then the dsb normalized data are added to. 

I'll be updating the vignette in the next couple days to include some points discussed here :https://github.com/niaid/dsb/issues/20 and will add this. 

thanks!

**Comment by MattPM** [comment]
Please see the updated documentation on the main github readme. (documentation will be updated on CRAN as well soon).
