### ISSUE TITLE
Error in cells$`Gene Expression`

### ISSUE THREAD

**Issue by rpauly** [niaid/dsb#27]
Hi,
Thank you for this package! I am excited to run it. However, I do get an error. Perhaps a bit naive error:
So I got the step fine:
# read raw data using the Seurat function "Read10X" 
raw = Seurat::Read10X("data/raw_feature_bc_matrix/")
cells = Seurat::Read10X("data/filtered_feature_bc_matrix/")

When I get to this step, it says:
# define a vector of cell-containing barcodes and remove them from unfiltered data 
stained_cells = colnames(cells$`Gene Expression`)

Error in cells$`Gene Expression` : 
  $ operator not defined for this S4 class

Am I missing a step?
Thanks.
Rini

**Comment by MattPM** [comment]
Hi, thanks for your interest in our method, this error message is upstream of our method and has to do with loading the raw data. First, this line assumes you used Cell Ranger for the alignment of your sequencing data, and that you have specified multiple library types in the alignment step: https://support.10xgenomics.com/single-cell-gene-expression/software/pipelines/latest/using/feature-bc-analysis 

Your starting raw and filtered data should be formatted with 3 subdirectories, e.g. within the raw_feature_be_matrix/ folder you should have 3 folders, features.tsv.gz, barcodes.tsv.gz, and matrix.mtx.gz

Within the features.tsv folder, there are 3 columns, the 3rd specifies what type of library (i.e. what data modality) the feature (gene or protein) is derived from. Usually at the end of the file you should see the protein and gene expression separately specified like so: 

ENSG00000276017	AC007325.1	Gene Expression
ENSG00000278817	AC007325.4	Gene Expression
ENSG00000277196	AC007325.2	Gene Expression
CD3	CD3	Antibody Capture
CD4	CD4	Antibody Capture
CD8	CD8	Antibody Capture
CD11c	CD11c	Antibody Capture

I would take a look at that first to make sure that Cell Ranger was properly run. 

By default, the Seurat function Read10X recognizes that there are multiple types of libraries (ADT and gene expression) by referring to the features file. If cell ranger was run correctly, you should have seen the following message about data types when you ran the command: 
`cells = Seurat::Read10X("data/filtered_feature_bc_matrix/")`
message in your r console: 
*10X data contains more than one type and is being returned as a list containing matrices of each type.*

Your error shows that R is recognizing the object `cells` as an object that is in the S4 class, so I think Seurat is properly installed....that makes me think the Seurat function above did not find multiple assays specified in the raw data. 

To troubleshoot this try downloading the filtered_bc_matrix from here https://support.10xgenomics.com/single-cell-gene-expression/datasets/6.0.0/1k_PBMCs_TotalSeq_B_3p? unzip the file put it in the data directory and load it with `Seurat::Read10X` like above, you should see the message about multiple assays. 

Let me know if you find the raw data properly specified, then I can help you troubleshoot further but I think that is the error.  I also recommend restarting your R session and trying again if you haven't done that to avoid package install conflicts; in addition, if the above does not solve the issue, please type in your reply what the output is of the function `sessionInfo()`

**Comment by rpauly** [comment]
Thanks ! That was so helpful, I got through several steps, but I am getting  errors here:
d = cbind(s@reductions$umap@cell.embeddings)
Error in cbind(s@reductions$umap@cell.embeddings) : 
  trying to get slot "cell.embeddings" from an object of a basic class ("NULL") with no slots.

What might be the issue?
<div style="color: rgb(0, 0, 0); font-family: &quot;Lucida Grande&quot;, serif; font-size: 12px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(246, 247, 249); text-decoration-style: initial; text-decoration-color: initial; position: absolute; overflow: hidden; z-index: 0; left: 0px; top: 0px; right: 0px; bottom: 611px;"><div role="region" aria-label="Source" class="windowframe GCHYANPCAW" style="-webkit-font-smoothing: subpixel-antialiased; position: absolute; left: 0px; top: 0px; right: 0px; bottom: 0px;"><div style="border: 1px solid rgb(214, 218, 220); border-radius: 3px 3px 0px 0px; left: 3px; top: 3px; right: 3px; bottom: 5px; overflow: hidden; position: absolute;"><div style="position: absolute; left: 0px; top: 0px; right: 0px; bottom: 0px;"><div style="position: relative; width: 888.547px; height: 249px;"><div style="position: absolute; overflow: hidden; left: 0px; top: 0px; right: 0px; bottom: 0px;"><div class="gwt-TabLayoutPanel GCHYANPCPP GCHYANPCES rstudio_source_panel" style="background: rgb(244, 248, 249); position: absolute; left: 0px; top: 0px; right: 0px; bottom: 0px;"><div style="top: 24px; position: absolute; overflow: hidden; left: 0px; right: 0px; bottom: 0px;"><div class="gwt-TabLayoutPanelContentContainer" style="position: absolute; left: 0px; top: 0px; right: 0px; bottom: 0px;"><div style="position: absolute; overflow: hidden; left: 0px; top: 0px; width: 888.547px; height: 226px;"><div role="tabpanel" aria-label="s Object Explorer" id="gwt-uid-530" class="gwt-TabLayoutPanelContent" style="background: rgb(244, 248, 249); width: 888.547px; height: 226px; position: absolute; left: 0px; top: 0px; right: 0px; bottom: 0px;"><div style="position: relative; width: 888.547px; height: 226px;"><div style="position: absolute; overflow: hidden; left: 0px; top: 22px; right: 0px; bottom: 0px;"><div class="ace_editor_theme" style="background-color: rgb(255, 255, 255); color: black; position: absolute; width: 888.547px; height: 204px; left: 0px; top: 0px; right: 0px; bottom: 0px;"><div style="position: absolute; overflow: hidden; left: 0px; right: 0px; bottom: 0px; height: 16px;"><div class="rstudio-themes-background GCHYANPCIOC" style="padding: 0px 4px; background: rgb(244, 248, 249); width: 888.547px; height: 16px; position: absolute; left: 0px; top: 0px; right: 0px; bottom: 0px;"><div class="gwt-Label GCHYANPCHOC" style="cursor: default; user-select: text; font-size: 11px; margin-top: 1px;">s@reductions</div></div></div><div style="position: absolute; overflow: hidden; left: 0px; top: 0px; right: 0px; bottom: 16px;"><div style="position: absolute; min-width: 20px; min-height: 20px; left: 0px; top: 0px; right: 0px; bottom: 0px;"><div aria-hidden="true" style="position: absolute; z-index: -32767; top: -20ex; width: 10em; height: 10ex; visibility: hidden;"></div><div style="visibility: hidden; position: absolute; height: 188px; width: 888.547px; overflow: hidden scroll; z-index: -1;"><div style="height: 288px; width: 989px;"></div></div><div style="visibility: hidden; position: absolute; height: 188px; width: 888.547px; overflow: hidden scroll; z-index: -1;"><div style="width: 1777.09px; height: 376px;"></div></div><div style="position: absolute; overflow: hidden; left: 0px; top: 0px; width: 888.547px; height: 188px;"><div __gwtcellbasedwidgetimpldispatchingfocus="true" __gwtcellbasedwidgetimpldispatchingblur="true" class="GCHYANPCPNC" style="font-size: 9pt; background-color: inherit; outline: none; position: absolute; overflow: hidden; width: 888.547px; height: 188px; left: 0px; top: 0px; right: 0px; bottom: 0px;"><div style="min-height: 20px; position: absolute; left: 0px; width: 888.547px; top: 0px; min-width: 20px; overflow: hidden;"><div style="visibility: hidden; position: absolute; height: 19px; width: 888.547px; overflow: hidden scroll; z-index: -1;"><div style="height: 119px; width: 989px;"></div></div><div style="visibility: hidden; position: absolute; height: 19px; width: 888.547px; overflow: hidden scroll; z-index: -1;"><div style="width: 1777.09px; height: 38px;"></div></div><div>

Name | Type | Value
-- | -- | --


</div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div>



***************************************************************************************************************************

> sessionInfo()
R version 4.0.4 (2021-02-15)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Catalina 10.15.7

Matrix products: default
BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/4.0/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] forcats_0.5.1      stringr_1.4.0      dplyr_1.0.7        purrr_0.3.4        readr_2.0.0       
 [6] tidyr_1.1.3        tibble_3.1.3       ggplot2_3.3.5      tidyverse_1.3.1    SeuratObject_4.0.2
[11] Seurat_4.0.3       dsb_0.1.0         

loaded via a namespace (and not attached):
  [1] Rtsne_0.15            colorspace_2.0-2      deldir_0.2-10         ellipsis_0.3.2        ggridges_0.5.3       
  [6] mclust_5.4.7          fs_1.5.0              rstudioapi_0.13       spatstat.data_2.1-0   farver_2.1.0         
 [11] leiden_0.3.9          listenv_0.8.0         ggrepel_0.9.1         fansi_0.5.0           lubridate_1.7.10     
 [16] xml2_1.3.2            codetools_0.2-18      splines_4.0.4         polyclip_1.10-0       jsonlite_1.7.2       
 [21] broom_0.7.9           ica_1.0-2             cluster_2.1.2         dbplyr_2.1.1          png_0.1-7            
 [26] pheatmap_1.0.12       uwot_0.1.10           shiny_1.6.0           sctransform_0.3.2     spatstat.sparse_2.0-0
 [31] compiler_4.0.4        httr_1.4.2            backports_1.2.1       assertthat_0.2.1      Matrix_1.3-4         
 [36] fastmap_1.1.0         lazyeval_0.2.2        cli_3.0.1             limma_3.46.0          later_1.2.0          
 [41] htmltools_0.5.1.1     tools_4.0.4           igraph_1.2.6          gtable_0.3.0          glue_1.4.2           
 [46] RANN_2.6.1            reshape2_1.4.4        tinytex_0.32          Rcpp_1.0.7            scattermore_0.7      
 [51] cellranger_1.1.0      vctrs_0.3.8           nlme_3.1-152          lmtest_0.9-38         xfun_0.24            
 [56] globals_0.14.0        rvest_1.0.1           mime_0.11             miniUI_0.1.1.1        lifecycle_1.0.0      
 [61] irlba_2.3.3           goftest_1.2-2         future_1.21.0         MASS_7.3-54           zoo_1.8-9            
 [66] scales_1.1.1          spatstat.core_2.3-0   hms_1.1.0             promises_1.2.0.1      spatstat.utils_2.2-0 
 [71] parallel_4.0.4        RColorBrewer_1.1-2    reticulate_1.20       pbapply_1.4-3         gridExtra_2.3        
 [76] rpart_4.1-15          stringi_1.7.3         rlang_0.4.11          pkgconfig_2.0.3       matrixStats_0.60.0   
 [81] lattice_0.20-44       ROCR_1.0-11           tensor_1.5            labeling_0.4.2        patchwork_1.1.1      
 [86] htmlwidgets_1.5.3     cowplot_1.1.1         tidyselect_1.1.1      parallelly_1.27.0     RcppAnnoy_0.0.19     
 [91] plyr_1.8.6            magrittr_2.0.1        R6_2.5.0              generics_0.1.0        DBI_1.1.1            
 [96] withr_2.4.2           pillar_1.6.2          haven_2.4.1           mgcv_1.8-36           fitdistrplus_1.1-5   
[101] survival_3.2-11       abind_1.4-5           future.apply_1.7.0    modelr_0.1.8          crayon_1.4.1         
[106] KernSmooth_2.23-20    utf8_1.2.2            spatstat.geom_2.2-2   plotly_4.9.4.1        tzdb_0.1.2           
[111] readxl_1.3.1          grid_4.0.4            data.table_1.14.0     reprex_2.0.0          digest_0.6.27        
[116] xtable_1.8-4          httpuv_1.6.1          munsell_0.5.0         viridisLite_0.4.0

**Comment by MattPM** [comment]
This is a Seurat question. A Seurat object is an 'S4' object which is similar to a R 'list'. When you modify the Seurat object, things populate the object in different places. When you run dimensionality reduction like PCA tsne or umap, they populate the 'reductions' slot in the object. 

You need to run umap first to be able to pull the cell embeddings (i.e. the position along umap dimension 1 and 2) from the 'reductions' slot. The error says that there is not any data in the reductions slot. The step below is just making a dataframe from relevant information in the Seurat object. If the Seurat object can't find any data in the reductions slot, then no dimensionality reductions were run with RunUMAP RunPCA etc. You can troubleshoot that error by looking at names(s@reductions). Is there anything there? 

Likely you did not run this step. 
```{r}
# umap for visualization only; (this is optional)
s = RunUMAP(object = s, assay = "CITE", features = prots, seed.use = 1990,
            min.dist = 0.2, n.neighbors = 30, verbose = FALSE)
```

If you don't run umap, you can just do: 

```
d = cbind(s@meta.data, as.data.frame(t(s@assays$CITE@data))) 
```

Maybe you didn't run because of my comment that it is optional. I more meant that it's up to you if you want to use UMAP to visualize your data; there are an infinite number of ways to squish high dimensional data into 2 dimensions. A umap plot can be helpful to get a feel for your data, but shouldn't be interpreted too much. Hopefully that is helpful (and sorry if you know all this already!) just providing some info and happy to help further.

**Comment by rpauly** [comment]
Thank you ..i appreciate your comments! I indeed did not run #umap visulization step.
My next query is after I plot a heatmap of the average dsb normalized values for each cluster (the heatmap is attached), and would like to annotate cell type based on median dsb normalized protein level per cluster. How do I assign the cell types?
For instance, how do I know if CD4_Tcell_Memory", # 0  or CD4_Tcell_Memory", # 13?
Sorry if this is a naive question!
![Rplot_sample_16_SNU_dsb_normalized](https://user-images.githubusercontent.com/1125723/128746863-83f47cfa-4d13-4632-a88c-3ca0dcb44e26.png)
Thanks,
Rini

**Comment by MattPM** [comment]
The cell types that are markers of certain clusters shown in the vignette are based on leveraging several decades of immunology studies characterizing cell types, states and functions via flow cytometry. Knowledge of certain cell types based on surface protein is a reason many are keen on using CITE-seq to further our knowledge of cell types and states. 

The exact markers of certain cell types present in a sample depends on the tissue begin profiled and the markers in the protein panel, it really depends on your data. For PBMC, I think the supplemental figures in this paper are a good place to start as many basic cell types present in PBMC are defined through the traditional biaxial flow cytometry plots. https://www.sciencedirect.com/science/article/pii/S2211124719300592 

There are also efforts to derive reference maps based on single cell data, for example maybe check out Azimuth from the Satija lab. 

Good luck!
