### ISSUE TITLE
dsb package environment

### ISSUE THREAD

**Issue by jjs847** [niaid/dsb#28]
Hi, 

I would like to add this package to an environment. I don't think it is available to bioconda or conda-forge, so I wanted to build a skeleton recipe in order to add this to my environment, however, when using conda-build r-dsb, I get the error "conda_build.exceptions.DependencyNeedsBuildingError: Unsatisfiable dependencies for platform linux-64: {'r-limma'}". I have bioconductor-limma in the environment already; I believe r-limma is the same package, and while I can get bioconductor-limma, I cannot get r-limma from anaconda (it is stuck on solving environment). 

Has this package already been made available on another channel? If not, is there anyway to install without r-limma? Is it the same as the bioconductor-limma package? I am new to using conda, so I apologize if what I describe isn't clear!

**Comment by MattPM** [comment]
@jjs847 closing this issue for now please feel free to open again if further assistance needed.
