### ISSUE TITLE
(denoise.counts=TRUE, use.isotype.control=TRUE) very similar (denoise.counts=FALSE, use.isotype.control=FALSE)

### ISSUE THREAD

**Issue by domi84** [niaid/dsb#37]
Hello,
thanks for this interesting package,
I am just using the code https://cran.r-project.org/web/packages/dsb/vignettes/end_to_end_workflow.html on a dataset I have to see what difference it can make. But I realized that having the option (denoise.counts = TRUE,   use.isotype.control = TRUE) or (denoise.counts = FALSE,   use.isotype.control = FALSE) return a very similar result...which surprise me .

This
```
cells.dsb.norm1 = DSBNormalizeProtein(
  cell_protein_matrix = cell.adt.raw,
  empty_drop_matrix = background.adt.mtx,
  denoise.counts = TRUE,
  use.isotype.control = TRUE,
  isotype.control.name.vec = isotype.controls
  )
```

takes longer time to run, and return:
[1] "correcting ambient protein background noise"
[1] "some proteins with low background variance detected check raw and normalized distributions.  protein stats can be returned with return.stats = TRUE"
[1] "Hu.CD48"  "Hu.CD11c" "Hu.CD31"  "Hu.CD62L" "Hu.CD36" 
[1] "fitting models to each cell for dsb technical component and removing cell to cell technical noise"

<html><body>

  | Hu.CD86<dbl> | Hu.CD274<dbl> | Hu.CD270<dbl> | Hu.CD155<dbl> | Hu.CD112<dbl> | Hu.CD47<dbl> | Hu.CD48<dbl> |  
-- | -- | -- | -- | -- | -- | -- | -- | --
0 | 1.944590 | 1.092919 | 1.101433 | 0.8200972 | 0.9423016 | 7.043330 | 1.31645800 |  
1 | 4.206515 | 1.143181 | 1.104835 | 0.9502019 | 0.9075726 | 10.947148 | -0.32764956 |  
2 | 2.777990 | 1.221543 | 1.247028 | 0.8633896 | 1.0350072 | 7.846072 | -0.06536306

</body>
</html>

while this:
```
cells.dsb.norm2 = DSBNormalizeProtein(
  cell_protein_matrix = cell.adt.raw,
  empty_drop_matrix = background.adt.mtx,
  denoise.counts = FALSE,
  use.isotype.control = FALSE
  )
```
is very quick, and return:
[1] "Not running dsb step II (removal of cell to cell technical noise) Setting use.isotype.control and isotype.control.name.vec to FALSE and NULL"
[1] "potential isotype controls detected: "
[1] "Isotype_MOPC.21"  "Isotype_MOPC.173" "Isotype_MPC.11"   "Isotype_RTK4530" 
[5] "Isotype_RTK2071"  "Isotype_G0114F7"  "Isotype_RTK2758"  "Isotype_RTK4174" 
[9] "Isotype_HTK888"  
[1] "correcting ambient protein background noise"
[1] "some proteins with low background variance detected check raw and normalized distributions.  protein stats can be returned with return.stats = TRUE"
[1] "Hu.CD48"  "Hu.CD11c" "Hu.CD31"  "Hu.CD62L" "Hu.CD36" 

<html><body>

  | Hu.CD86<dbl> | Hu.CD274<dbl> | Hu.CD270<dbl> | Hu.CD155<dbl> | Hu.CD112<dbl> | Hu.CD47<dbl> | Hu.CD48<dbl> |  
-- | -- | -- | -- | -- | -- | -- | -- | --
0 | 1.582482 | 1.052647 | 1.120445 | 0.9469014 | 0.9177784 | 7.094805 | 1.4910953 |  
1 | 4.205012 | 1.052647 | 1.120445 | 0.9469014 | 0.9177784 | 10.995484 | -0.4915249 |  
2 | 2.981426 | 1.306219 | 1.324305 | 0.9469014 | 0.9177784 | 8.029984 | -0.4915249 |  

</body>
</html>

which is different of course, but surprising similar, even the heatmaps looks identical
![image](https://user-images.githubusercontent.com/1794097/227738113-c0413e51-8645-44f5-9266-b5056dae15c5.png)
Also FeaturePlot/VlnPlot looks very similar

Am I doing anything wrong?
Thanks

**Comment by MattPM** [comment]
The correction in step II is often a smaller adjustment. A heatmap will not really show difference between dsb with or without step II, since this is adjusting cell to cell variations and the mean values will probably be similar. You could look at the differences when doing some protein-protein correlations to get a feel for the the changes in cell to cell variation that this step has. In particular, values of a single protein within a single cell type at the cell to cell level, for example.  In this particular dataset it does look like step II has a relatively small effect, based on a few cells you showed, but the values are different and those differences and the larger differences you might see in other cells are due to removal of technical cell to cell variations.
