### ISSUE TITLE
Do Isotype Control Values have to be Subtracted?

### ISSUE THREAD

**Issue by codeneeded** [niaid/dsb#38]
Since we have not specified which isotype control corresponds to which antibody, rather simply which of our antibodies are isotype controls.

Then, after normalization, do we need to subtract the isotype control values from their respective antibodies?

This is prior to interpreting AverageExpression() and FindMarkers() using Seurat.

**Comment by codeneeded** [comment]
Another question, when creating a seurat object, unlike RNA where we obtain in the metadata nCount_RNA and nFeature_RNA we the nCount_ADT and nFeature_ADT are empty.

**Comment by MattPM** [comment]
Hi @codeneeded For your first question, please see here https://github.com/niaid/dsb/issues/2 No after you use the method you shouldn't subtract isotype values, the isotypes are incorporated into the normalization in a different way. The paper explains how it works in this paragraph "Shared variance between isotype controls and background protein counts in single cells provide cell-intrinsic normalization factors" 

Re the second question, 
"unlike RNA where we obtain in the metadata nCount_RNA and nFeature_RNA we the nCount_ADT and nFeature_ADT are empty." This is a question about Seurat. Depending how you create an assay object this metadata may get added. You can also calculate those yourself if you want with rowsums and colsums, and add that to cell metadata, that's what Seurat does. Our tutorial explains how to calculate these (nCount_ADT and nFeature_ADT) and do QC on the data. 

Hope that answers your questions.
