### ISSUE TITLE
DSB with high throughput method

### ISSUE THREAD

**Issue by ojbednar** [niaid/dsb#42]
Hello! I recently completed a large CITE-seq experiment where I pulled 8 samples together for high throughput sequencing, so I have a hashtag antibody that I stained each cell with. Does the DSB workflow still work with this particular dataset or will the strong expression of the hashtags skew the protein expression? 

Thank you for your time.

**Comment by MattPM** [comment]
Hi I suggest reading through the documentation and FAQ sections of the vignettes for the package which detail how to use hashing antibodies with the workflow. We use cell hashing for all experiments. Hashing does not skew the protein expression. You may want to have a look at the methods section of the papers below as well. 
Best of luck, 
Matt 
https://doi.org/10.1016/j.cell.2021.02.018 
https://www.medrxiv.org/content/10.1101/2023.03.20.23287474v1
