### ISSUE TITLE
Selecting Cut-Off Value For ADT Expression

### ISSUE THREAD

**Issue by codeneeded** [niaid/dsb#43]
In the vignette and publication, you recommend to set a threshold across all proteins for positivity. In your publication, you have selected 3.5. 

I'm thinking you take your isotype controls and put positivity above that?

![image](https://github.com/niaid/dsb/assets/123397843/a5afb11c-8424-4db2-ae0a-0e086bc1e3ee)

To justify this how would I generate something like this where I can show my threshold and expressed/unexpressed?

2. How would this threshold be applied to the differential expression? Do I need to subtract some value during differential expression or would we have to set the values of all proteins deemed unexpressed (under the threshold) to 0 and then perform differential expression? If so, how would we do that?

Thanks so much for your help!

**Comment by MattPM** [comment]
Hi @codeneeded I'd check out the first section of the paper for more info on that threshold. After you normalize with dsb, a value above 3.5 reflects 3.5 standard deviations above ambient noise, ±adjustment for the cell intrinsic technical component. 

Any threshold you use has that same interpretation - the number of sd above ambient background noise with the correction for isotype controls already baked in. 3.5 s.d above ambient background noise applied across all proteins worked well on our datasets in the paper and some other projects but you could use another value. 

More explained in section 1:
https://www.nature.com/articles/s41467-022-29356-8

**Comment by codeneeded** [comment]
Thanks for your response. To give some background;

1 I have a Stim and Unstim condition. The isotype background is much higher for the stim when compared to the unstim. I have attached below (S is stim, M is unstim);

![Isotype_Threshold](https://github.com/niaid/dsb/assets/123397843/46a40b86-2efd-4ebc-af65-7979457c4308)

This is after DSB normalization. What I wanted to do was for each sample, I would subtract each protein that corresponds to its isotype with the 99% threshold of its isotype control. Then I would set all negative values to 0 or unexpressed. This would be done on a per-sample basis- does this make sense to control for this kind of sample-specific disparity in isotype control protein expression?
