### ISSUE TITLE
DSB validity for limited ADT features

### ISSUE THREAD

**Issue by saimaniharreddy** [niaid/dsb#46]
i have read your paper and have seen your vignettes. I understood that this was created for 14 ADT protein levels. The data that I'm currently working on, as only 4 ADT feature data. How reliable is the DSB method for normalizing this. If no what could be a better approach?

**Comment by MattPM** [comment]
Hi @saimaniharreddy we show in the paper that the method can be used with _as few_ as 14 proteins (up to hundreds). If you only have 4 ADTs then the 2 component mixture model used in the second step of the method will likely be unstable unless all of the proteins are positive on all of your cells. 
You can still use the method, just set `denoise.counts = FALSE` to implement step I only.
